package chromatic

const (
	C            = "C"
	CSharp       = "C#"
	CDoubleSharp = "C##"
	DFlat        = "Db"
	D            = "D"
	DSharp       = "D#"
	EFlat        = "Eb"
	E            = "E"
	ESharp       = "E#"
	F            = "F"
	FSharp       = "F#"
	FDoubleSharp = "F##"
	GFlat        = "Gb"
	G            = "G"
	GSharp       = "G#"
	AFlat        = "Ab"
	A            = "A"
	ASharp       = "A#"
	BFlat        = "Bb"
	B            = "B"
	BSharp       = "B#"
)
